# Generated by Django 2.1.1 on 2018-09-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180909_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
